parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
          string $cacheDir: '%kernel.cache_dir%'

    _instanceof:
        SymfonyTools\CodeBlockChecker\Service\CodeValidator\Validator:
            tags:
                - 'app.code_validator'

    SymfonyTools\CodeBlockChecker\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/Application.php'

    SymfonyTools\CodeBlockChecker\Service\CodeValidator:
        arguments: [!tagged_iterator app.code_validator]
