name: CI

on:
  pull_request:

jobs:
  build:
    name: Test
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Run demo
        run: echo "::error file=README.md,line=7::[XML syntax] Foo+%22bar%22+not+foo.Unescaped+%27%3C%27+not+allowed+in+attributes+values"
